name: Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "30 9 * * 1"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.5.3-focal
          - swift:5.9.2-focal
          - swift:5.10.1-noble
    container: ${{ matrix.image }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
      - name: Run Tests
        run: swift test --enable-test-discovery
  nextstep:
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
      - name: Run Tests
        run: swift test
